language: node_js
node_js:
    - 13
    - 12
    - 10
    - 8

script:
  - npm run codestyle
  - npm run coverage && npm run report

notifications:
    email:
        on_success: change
        on_failure: change

sudo: false

